version: "3"
services:
  app:
    container_name: devops-workshop-express
    restart: always
    build: ./
    ports:
      - "8787:8787"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"